/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1.ex1.presentation;

import java.awt.Button;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.j2ee.statistics.JCAConnectionPoolStats;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import tp1ex1.business.ObjectManager;
import tp1ex1.dao.Appointment;
import tp1ex1.dao.Medecin;
import tp1ex1.dao.Patient;
import tp1ex1.dao.TimeSlot;

/**
 *
 * @author Gaetan
 */
public class ApplicationFrame extends javax.swing.JFrame {
   
    private static final Class[] ENTITY_CLASSES = new Class[]{Medecin.class,Patient.class,TimeSlot.class, Appointment.class};
    private static final String[] ACTIONS = new String[]{"findAll","save","delete","exists"};
    private static final String BUSINESS_PACKAGE = "tp1ex1.business";

    /**
     * Creates new form ApplicationFrame
     */
    public ApplicationFrame() {
        initComponents();
        generateUIForEntities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPanel;
    // End of variables declaration//GEN-END:variables

    private void generateUIForEntities() {
        Class[] classes = ENTITY_CLASSES;
        
        if(classes != null) {
            for(Class c : classes) {
                JComponent currentPanel = generateUIForEntityClass(c);
                jTabbedPanel.addTab(c.getSimpleName(), currentPanel);
            }
        }
    }

    
    private JComponent generateUIForEntityClass(Class entityClass) {
        Field[] fields = entityClass.getDeclaredFields();
        JComponent currentComp =  new JPanel();
        currentComp.setPreferredSize(getSize());
        currentComp.setLayout(new GridLayout(fields.length, 2));
        
        for(Field currentField : fields) {
            if(currentField.getName().equals("serialVersionUID")) {
                continue;
            }
            
            currentComp.add(new JLabel(currentField.getName()));
            currentComp.add(new JTextField());
        }
        
        generateButtonsForActions(currentComp,entityClass);
        
        return currentComp;
    }

    private void generateButtonsForActions(JComponent currentComp, Class entityClass) {
        String entityName = entityClass.getSimpleName();
        String managerName = entityName + "Manager";
        Class manager = null;
        try {
             manager = Class.forName(BUSINESS_PACKAGE + "." + managerName);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ApplicationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(manager!= null) {
            
            JPanel buttonPanel = new JPanel(new FlowLayout());
            for(String s : ACTIONS) {
                buttonPanel.add(new JButton(s));
            }
            currentComp.add(buttonPanel);
        }
        
        
    }
    
}
